### ISSUE TITLE
Not working with WN722N V3 in VM

### ISSUE THREAD

**Issue by hoang-himself** [quickreflex/rtl8188eus#10]
```
airmon-ng

PHY	Interface	Driver		Chipset
phy0	wlan0		rtl8188eu
```
```
uname -r
4.17.0-kali1-amd64
```
Does this driver even support virtual machines?

**Comment by tristanlemoigne** [comment]
Yes, same for me. It passing mode to auto instead of monitor.
I am using virtualbox and WN722N V3

**Comment by Po-Hsuan-Huang** [comment]
Same here. I was using WN722N V3, for kernel 4.15. Not in VM though. signal shows connected but cannot connect to server.

**Comment by Smithienious** [comment]
It's still not working on both my virtual and physical machine. I tried switching between USB 2.0 and 3.0 but it doesn't change anything.
