### ISSUE TITLE
RTL 8188eu not recognized on ubuntu 18.04

### ISSUE THREAD

**Issue by Orsontrius** [quickreflex/rtl8188eus#29]
Hi, Im on ubuntu 18.04 with kernel version 5.1.0, there were no errors with the installation, but the device is not recognized. 

the command ifconfig wlan0 down returns:
wlan0: ERROR while getting interface flags: No such device

the device is listed by lsusb

**Comment by Orsontrius** [comment]
I should add that the device is listed by lsusb

**Comment by Orsontrius** [comment]
Closing as my device was labeled as rtl8188eu but is actually a rtl8188fu, installing the appropriate drivers solved my problem.

**Comment by digikar99** [comment]
@Orsontrius, how did you discover this?

EDIT: The device was working in Windows 10; so got the details from there; anyways, thanks for the hint!
