### ISSUE TITLE
i made it , monitor mode working on rtl8188eus ( tl-wn722n v3)

### ISSUE THREAD

**Issue by hameddanesh** [quickreflex/rtl8188eus#30]
hey guys i finally made it work thanks to tips on quickreflex and driver version 5.3.9 on kimocoder
to make monitoring work on kali linux rolling 2019 frist you have to use 4.19 kernell which is kali rolling 2019.a1 orginal kernel ( or install a lower kernal ( a linux image )
then go to :
https://github.com/kimocoder/rtl8188eus/tree/v5.3.9
download the driver , extract it in a folder , right click in folder and choose Open in termianl
and then enter these commands :
make clean
make all
cp realtek_blacklist.conf /lib/modprobe.d/
make install
reboot

to activate monitor mode : 
ifconfig <wlan name> down
iwconfig <wlan name> mode monitor
ifconfig <wlan name> up

i worked 3 day to find this , i hope this way will work for you too.
but even if not this is at least answer for a question most of us have : yes tl-wn722n v3 ( rtl8188eus chipset ) do work on monitoring mode in kali linux.

**Comment by preaverage** [comment]
Hey can I get your discord so you can help me out since you've most likely went through this.

**Comment by wallyradburn** [comment]
i get the following error in terminal when running the cp command :
cp: missing destination file operand after realtek_blacklist.conf /lib/modprobe.d/

can anyone help me with this please

**Comment by hameddanesh** [comment]
> i get the following error in terminal when running the cp command :
> cp: missing destination file operand after realtek_blacklist.conf /lib/modprobe.d/
> 
> can anyone help me with this please

well did you check the kernel version ? 🤔

**Comment by php717** [comment]
TP-LINK official have a good full manual how to do driver install 
https://www.tp-link.com/ae/support/download/tl-wn722n/v3/#Driver
going to try now..
shame that nethunter 2020 edition dont have drivers preloaded

**Comment by benkio** [comment]
A little comment, to compile the driver https://github.com/kimocoder/rtl8188eus/tree/v5.3.9
Use gcc-7!! I have gcc 7.5

now I continue :crossed_fingers:

**Comment by Chris-Zoumbos** [comment]
Is there any way to use the beta drivers on the latest Kali Linux?

**Comment by UchihaItachi1416** [comment]
Can someone make a tutorial how to do everything? I'm new to this and can't even understand a thing!

**Comment by TuserAhammed** [comment]
Tell me sir,,, Tp link wn722n V3 is working in nethunte??   And package injection  is working or not??? And  can i used this v3 adapter in fluxio???

**Comment by Zura001** [comment]
> i get the following error in terminal when running the cp command :
> cp: missing destination file operand after realtek_blacklist.conf /lib/modprobe.d/
> 
> can anyone help me with this please

Delete the "/" after modprob.d

**Comment by namanh2710** [comment]
tksssss so much it worked !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by farhadankhi** [comment]
I tried my best to install the driver for my kali Linux but I couldn't. Can anyone help me pls?

**Comment by GetRektBoy724** [comment]
if you're using Kali Linux or you have kali linux's repository, just install `realtek-rtl8188eus-dkms` with apt

**Comment by farhadankhi** [comment]
I am using kali Linux with VM Virtual Box...

**Comment by farhadankhi** [comment]
> if you're using Kali Linux or you have kali linux's repository, just install `realtek-rtl8188eus-dkms` with apt

what do you mean by "with apt"?
